environment:
  global:
      PYTHON: "C:\\conda"
      CONDA_ENVIRONMENT: "environment.yml"
      PIP_DEPENDENCIES: "codecov pytest-faulthandler"
  matrix:
      - PYTHON_VERSION: "2.7"
        PYTHON_ARCH: "64"

install:
  - "git clone --depth 1 git://github.com/astropy/ci-helpers.git"
  - "powershell ci-helpers/appveyor/install-miniconda.ps1"
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "activate test"
  - "git clone git://github.com/mne-tools/mne-bids.git"
  - "python setup.py develop"
  - "SET MNE_FORCE_SERIAL=true"  # otherwise joblib will bomb

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  # Run the project tests, but (sadly) exclude ones that take a long time
  - "py.test mne-bids --cov=mne-bids"

on_success:
- "codecov"
